/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ControlRouteImport } from './routes/control'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminSlugRouteImport } from './routes/$adminSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorLookupRouteImport } from './routes/vendor.lookup'
import { Route as VendorFinanceRouteImport } from './routes/vendor.finance'
import { Route as VendorCustomersRouteImport } from './routes/vendor.customers'
import { Route as VendorComplaintsRouteImport } from './routes/vendor.complaints'
import { Route as VendorAnalyticsRouteImport } from './routes/vendor.analytics'
import { Route as SuperadminVendorsRouteImport } from './routes/superadmin.vendors'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminSecurityRouteImport } from './routes/superadmin.security'
import { Route as SuperadminPayoutsRouteImport } from './routes/superadmin.payouts'
import { Route as SuperadminOrdersRouteImport } from './routes/superadmin.orders'
import { Route as SuperadminMarketingRouteImport } from './routes/superadmin.marketing'
import { Route as SuperadminFinanceRouteImport } from './routes/superadmin.finance'
import { Route as SuperadminDisputesRouteImport } from './routes/superadmin.disputes'
import { Route as SuperadminCustomersRouteImport } from './routes/superadmin.customers'
import { Route as SuperadminCouponsRouteImport } from './routes/superadmin.coupons'
import { Route as SuperadminContentRouteImport } from './routes/superadmin.content'
import { Route as SuperadminComplaintsRouteImport } from './routes/superadmin.complaints'
import { Route as SuperadminAnalyticsRouteImport } from './routes/superadmin.analytics'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/$adminSlug',
  path: '/$adminSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorLookupRoute = VendorLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => VendorRoute,
} as any)
const VendorFinanceRoute = VendorFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => VendorRoute,
} as any)
const VendorCustomersRoute = VendorCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => VendorRoute,
} as any)
const VendorComplaintsRoute = VendorComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAnalyticsRoute = VendorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VendorRoute,
} as any)
const SuperadminVendorsRoute = SuperadminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSecurityRoute = SuperadminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminPayoutsRoute = SuperadminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminOrdersRoute = SuperadminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminMarketingRoute = SuperadminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminFinanceRoute = SuperadminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDisputesRoute = SuperadminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCustomersRoute = SuperadminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCouponsRoute = SuperadminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminContentRoute = SuperadminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminComplaintsRoute = SuperadminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAnalyticsRoute = SuperadminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperadminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$adminSlug': typeof AdminSlugRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/complaints': typeof SuperadminComplaintsRoute
  '/superadmin/content': typeof SuperadminContentRoute
  '/superadmin/coupons': typeof SuperadminCouponsRoute
  '/superadmin/customers': typeof SuperadminCustomersRoute
  '/superadmin/disputes': typeof SuperadminDisputesRoute
  '/superadmin/finance': typeof SuperadminFinanceRoute
  '/superadmin/marketing': typeof SuperadminMarketingRoute
  '/superadmin/orders': typeof SuperadminOrdersRoute
  '/superadmin/payouts': typeof SuperadminPayoutsRoute
  '/superadmin/security': typeof SuperadminSecurityRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/vendors': typeof SuperadminVendorsRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/complaints': typeof VendorComplaintsRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/finance': typeof VendorFinanceRoute
  '/vendor/lookup': typeof VendorLookupRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$adminSlug': typeof AdminSlugRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/complaints': typeof SuperadminComplaintsRoute
  '/superadmin/content': typeof SuperadminContentRoute
  '/superadmin/coupons': typeof SuperadminCouponsRoute
  '/superadmin/customers': typeof SuperadminCustomersRoute
  '/superadmin/disputes': typeof SuperadminDisputesRoute
  '/superadmin/finance': typeof SuperadminFinanceRoute
  '/superadmin/marketing': typeof SuperadminMarketingRoute
  '/superadmin/orders': typeof SuperadminOrdersRoute
  '/superadmin/payouts': typeof SuperadminPayoutsRoute
  '/superadmin/security': typeof SuperadminSecurityRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/vendors': typeof SuperadminVendorsRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/complaints': typeof VendorComplaintsRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/finance': typeof VendorFinanceRoute
  '/vendor/lookup': typeof VendorLookupRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/account': typeof AccountIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$adminSlug': typeof AdminSlugRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/complaints': typeof SuperadminComplaintsRoute
  '/superadmin/content': typeof SuperadminContentRoute
  '/superadmin/coupons': typeof SuperadminCouponsRoute
  '/superadmin/customers': typeof SuperadminCustomersRoute
  '/superadmin/disputes': typeof SuperadminDisputesRoute
  '/superadmin/finance': typeof SuperadminFinanceRoute
  '/superadmin/marketing': typeof SuperadminMarketingRoute
  '/superadmin/orders': typeof SuperadminOrdersRoute
  '/superadmin/payouts': typeof SuperadminPayoutsRoute
  '/superadmin/security': typeof SuperadminSecurityRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/vendors': typeof SuperadminVendorsRoute
  '/vendor/analytics': typeof VendorAnalyticsRoute
  '/vendor/complaints': typeof VendorComplaintsRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/finance': typeof VendorFinanceRoute
  '/vendor/lookup': typeof VendorLookupRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$adminSlug'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/control'
    | '/login'
    | '/signup'
    | '/superadmin'
    | '/vendor'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/superadmin/analytics'
    | '/superadmin/complaints'
    | '/superadmin/content'
    | '/superadmin/coupons'
    | '/superadmin/customers'
    | '/superadmin/disputes'
    | '/superadmin/finance'
    | '/superadmin/marketing'
    | '/superadmin/orders'
    | '/superadmin/payouts'
    | '/superadmin/security'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/superadmin/vendors'
    | '/vendor/analytics'
    | '/vendor/complaints'
    | '/vendor/customers'
    | '/vendor/finance'
    | '/vendor/lookup'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/account/'
    | '/superadmin/'
    | '/vendor/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$adminSlug'
    | '/cart'
    | '/checkout'
    | '/control'
    | '/login'
    | '/signup'
    | '/account/addresses'
    | '/account/profile'
    | '/account/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/superadmin/analytics'
    | '/superadmin/complaints'
    | '/superadmin/content'
    | '/superadmin/coupons'
    | '/superadmin/customers'
    | '/superadmin/disputes'
    | '/superadmin/finance'
    | '/superadmin/marketing'
    | '/superadmin/orders'
    | '/superadmin/payouts'
    | '/superadmin/security'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/superadmin/vendors'
    | '/vendor/analytics'
    | '/vendor/complaints'
    | '/vendor/customers'
    | '/vendor/finance'
    | '/vendor/lookup'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/account'
    | '/superadmin'
    | '/vendor'
    | '/account/orders/$id'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/$adminSlug'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/control'
    | '/login'
    | '/signup'
    | '/superadmin'
    | '/vendor'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/category/$slug'
    | '/product/$slug'
    | '/superadmin/analytics'
    | '/superadmin/complaints'
    | '/superadmin/content'
    | '/superadmin/coupons'
    | '/superadmin/customers'
    | '/superadmin/disputes'
    | '/superadmin/finance'
    | '/superadmin/marketing'
    | '/superadmin/orders'
    | '/superadmin/payouts'
    | '/superadmin/security'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/superadmin/vendors'
    | '/vendor/analytics'
    | '/vendor/complaints'
    | '/vendor/customers'
    | '/vendor/finance'
    | '/vendor/lookup'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/account/'
    | '/superadmin/'
    | '/vendor/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSlugRoute: typeof AdminSlugRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ControlRoute: typeof ControlRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$adminSlug': {
      id: '/$adminSlug'
      path: '/$adminSlug'
      fullPath: '/$adminSlug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/lookup': {
      id: '/vendor/lookup'
      path: '/lookup'
      fullPath: '/vendor/lookup'
      preLoaderRoute: typeof VendorLookupRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/finance': {
      id: '/vendor/finance'
      path: '/finance'
      fullPath: '/vendor/finance'
      preLoaderRoute: typeof VendorFinanceRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/customers': {
      id: '/vendor/customers'
      path: '/customers'
      fullPath: '/vendor/customers'
      preLoaderRoute: typeof VendorCustomersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/complaints': {
      id: '/vendor/complaints'
      path: '/complaints'
      fullPath: '/vendor/complaints'
      preLoaderRoute: typeof VendorComplaintsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/analytics': {
      id: '/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof VendorAnalyticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/superadmin/vendors': {
      id: '/superadmin/vendors'
      path: '/vendors'
      fullPath: '/superadmin/vendors'
      preLoaderRoute: typeof SuperadminVendorsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/security': {
      id: '/superadmin/security'
      path: '/security'
      fullPath: '/superadmin/security'
      preLoaderRoute: typeof SuperadminSecurityRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/payouts': {
      id: '/superadmin/payouts'
      path: '/payouts'
      fullPath: '/superadmin/payouts'
      preLoaderRoute: typeof SuperadminPayoutsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/orders': {
      id: '/superadmin/orders'
      path: '/orders'
      fullPath: '/superadmin/orders'
      preLoaderRoute: typeof SuperadminOrdersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/marketing': {
      id: '/superadmin/marketing'
      path: '/marketing'
      fullPath: '/superadmin/marketing'
      preLoaderRoute: typeof SuperadminMarketingRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/finance': {
      id: '/superadmin/finance'
      path: '/finance'
      fullPath: '/superadmin/finance'
      preLoaderRoute: typeof SuperadminFinanceRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/disputes': {
      id: '/superadmin/disputes'
      path: '/disputes'
      fullPath: '/superadmin/disputes'
      preLoaderRoute: typeof SuperadminDisputesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/customers': {
      id: '/superadmin/customers'
      path: '/customers'
      fullPath: '/superadmin/customers'
      preLoaderRoute: typeof SuperadminCustomersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/coupons': {
      id: '/superadmin/coupons'
      path: '/coupons'
      fullPath: '/superadmin/coupons'
      preLoaderRoute: typeof SuperadminCouponsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/content': {
      id: '/superadmin/content'
      path: '/content'
      fullPath: '/superadmin/content'
      preLoaderRoute: typeof SuperadminContentRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/complaints': {
      id: '/superadmin/complaints'
      path: '/complaints'
      fullPath: '/superadmin/complaints'
      preLoaderRoute: typeof SuperadminComplaintsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/analytics': {
      id: '/superadmin/analytics'
      path: '/analytics'
      fullPath: '/superadmin/analytics'
      preLoaderRoute: typeof SuperadminAnalyticsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface SuperadminRouteChildren {
  SuperadminAnalyticsRoute: typeof SuperadminAnalyticsRoute
  SuperadminComplaintsRoute: typeof SuperadminComplaintsRoute
  SuperadminContentRoute: typeof SuperadminContentRoute
  SuperadminCouponsRoute: typeof SuperadminCouponsRoute
  SuperadminCustomersRoute: typeof SuperadminCustomersRoute
  SuperadminDisputesRoute: typeof SuperadminDisputesRoute
  SuperadminFinanceRoute: typeof SuperadminFinanceRoute
  SuperadminMarketingRoute: typeof SuperadminMarketingRoute
  SuperadminOrdersRoute: typeof SuperadminOrdersRoute
  SuperadminPayoutsRoute: typeof SuperadminPayoutsRoute
  SuperadminSecurityRoute: typeof SuperadminSecurityRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminVendorsRoute: typeof SuperadminVendorsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAnalyticsRoute: SuperadminAnalyticsRoute,
  SuperadminComplaintsRoute: SuperadminComplaintsRoute,
  SuperadminContentRoute: SuperadminContentRoute,
  SuperadminCouponsRoute: SuperadminCouponsRoute,
  SuperadminCustomersRoute: SuperadminCustomersRoute,
  SuperadminDisputesRoute: SuperadminDisputesRoute,
  SuperadminFinanceRoute: SuperadminFinanceRoute,
  SuperadminMarketingRoute: SuperadminMarketingRoute,
  SuperadminOrdersRoute: SuperadminOrdersRoute,
  SuperadminPayoutsRoute: SuperadminPayoutsRoute,
  SuperadminSecurityRoute: SuperadminSecurityRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminVendorsRoute: SuperadminVendorsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface VendorRouteChildren {
  VendorAnalyticsRoute: typeof VendorAnalyticsRoute
  VendorComplaintsRoute: typeof VendorComplaintsRoute
  VendorCustomersRoute: typeof VendorCustomersRoute
  VendorFinanceRoute: typeof VendorFinanceRoute
  VendorLookupRoute: typeof VendorLookupRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorAnalyticsRoute: VendorAnalyticsRoute,
  VendorComplaintsRoute: VendorComplaintsRoute,
  VendorCustomersRoute: VendorCustomersRoute,
  VendorFinanceRoute: VendorFinanceRoute,
  VendorLookupRoute: VendorLookupRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSlugRoute: AdminSlugRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ControlRoute: ControlRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
